### ISSUE TITLE
Create header

### ISSUE THREAD

**Issue by anasAsh** [jordanopensource/wp-josa#1]
as a user i should be able to see the header as in the attached image.

as an admin, i should be able to change menu items and logo from the admin dashboard.

![header](https://user-images.githubusercontent.com/1830449/42411065-ee245056-81fd-11e8-9150-f33aca3147f2.png)

**Comment by anasAsh** [comment]
@mahasneh: two questions:
1- should we add language switcher here?
2- would you please provide a logo with arabic text?

note to developer: 
we need to find a way to change the logo with the language, arabic for arabic, english for english.

**Comment by mahasneh** [comment]
There should be a link to the Arabic version (when the Arabic version will be available), the English version should have a link to the Arabic one.
![flowroot7051-3-9-1-5-2](https://user-images.githubusercontent.com/7326249/42411143-80efed54-81ff-11e8-8e40-4a1f1f7c27e4.png)
